# Generated by Django 5.0.2 on 2025-02-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebookapp', '0002_recipe_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
