# Generated by Django 5.0.2 on 2025-02-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebookapp', '0003_remove_recipe_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('snack', 'Перекус'), ('lunch', 'Обед'), ('dinner', 'Ужин')], default='snack', max_length=20, verbose_name='Тип приема пищи'),
        ),
    ]
